"""fixed categories

Revision ID: 3bd7ea48fa61
Revises: 86d80ac037dc
Create Date: 2023-08-14 06:09:38.463582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd7ea48fa61'
down_revision: Union[str, None] = '86d80ac037dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questions', 'difficulties', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # ### end Alembic commands ###
